include ../../../Makefile.conf

ROOT_DIR := $(BUILD_DIR)/../../..
TARGET := short_bouncing_ball.smv
LOG_FILE := $(TARGET:.smv=.log)
PROVE_ARGS += --reset=_rst --prop=1

include ../../../Makefile.build
