include ../../../../Makefile.conf

ROOT_DIR := $(BUILD_DIR)/../../../../
TARGET := dac.smv
LOG_FILE := $(TARGET:.smv=_prop1.log)
PROVE_ARGS += --reset=_rst --prop=1

include ../../../../Makefile.build
